# Generated by Django 5.1.15 on 2026-08-22 06:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('APPROVE', 'Approve'), ('REJECT', 'Reject')], db_index=True, max_length=20)),
                ('entity_type', models.CharField(db_index=True, help_text='Model name (e.g., Employee, Department, LeaveRequest).', max_length=100)),
                ('entity_id', models.CharField(db_index=True, help_text='Primary key of the affected entity.', max_length=255)),
                ('old_values', models.JSONField(blank=True, help_text='Previous state.', null=True)),
                ('new_values', models.JSONField(blank=True, help_text='New state.', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='organizations.organization')),
            ],
            options={
                'ordering': ['-created_at'],
                'managed': True,
                'indexes': [models.Index(fields=['organization', 'entity_type', '-created_at'], name='audit_audit_organiz_8600cd_idx'), models.Index(fields=['actor', '-created_at'], name='audit_audit_actor_i_1175ab_idx')],
            },
        ),
    ]
