# Generated by Django 5.1.15 on 2026-08-22 06:08

import common.storage
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('organization_code', models.CharField(db_index=True, help_text="Unique code for the organization, used in employee IDs (e.g., 'OI').", max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('address', models.TextField(blank=True, default='')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=common.storage.organization_logo_path)),
                ('timezone', models.CharField(default='UTC', help_text="IANA timezone (e.g., 'Asia/Kolkata', 'US/Eastern').", max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['organization_code'], name='organizatio_organiz_913450_idx'), models.Index(fields=['is_active'], name='organizatio_is_acti_1ffc28_idx')],
            },
        ),
    ]
